### ISSUE TITLE
Crashes on Resume for startPreview

### ISSUE THREAD

**Issue by snehabhegade** [google/cameraview#212]
Caused by: java.lang.RuntimeException: startPreview failed                                                                   
    at android.hardware.Camera.startPreview(Native Method) at 
    com.google.android.cameraview.Camera1.start(Camera1.java:95)                                                                    
    at com.google.android.cameraview.CameraView.start(CameraView.java:252)

**Comment by Sp4Rx** [comment]
Any solution?
