### ISSUE TITLE
Caused by: java.lang.RuntimeException: Fail to connect to camera service

### ISSUE THREAD

**Issue by zhaoyangxihui** [google/cameraview#276]

**Comment by zhaoyangxihui** [comment]
at android.hardware.Camera.<init>(Camera.java:575)
        at android.hardware.Camera.open(Camera.java:404)
        at com.google.android.cameraview.Camera1.openCamera(Camera1.java:276)
        at com.google.android.cameraview.Camera1.start(Camera1.java:89)
        at com.google.android.cameraview.CameraView.start(CameraView.java:250)
        at com.eva.gen3.awake.activity.set.panel.advanced.CustomCameraTestActivity.onResume(CustomCameraTestActivity.java:90)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
        at android.app.Activity.performResume(Activity.java:6827)

**Comment by ghiyatshanif** [comment]
how did you solve this issue?
