### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by anvesh523** [google/cameraview#5]
FATAL EXCEPTION: main
                                                                                  Process: com.google.android.cameraview.demo, PID: 3438
                                                                                  java.lang.RuntimeException: Unable to resume activity {com.google.android.cameraview.demo/com.google.android.cameraview.demo.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
                                                                                      at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)
                                                                                      at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
                                                                                      at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                   Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
                                                                                      at com.google.android.cameraview.Camera2.chooseCameraIdByFacing(Camera2.java:388)
                                                                                      at com.google.android.cameraview.Camera2.start(Camera2.java:233)
                                                                                      at com.google.android.cameraview.CameraView.start(CameraView.java:226)
                                                                                      at com.google.android.cameraview.demo.MainActivity.onResume(MainActivity.java:140)
                                                                                      at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1258)
                                                                                      at android.app.Activity.performResume(Activity.java:6312)
                                                                                      at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
                                                                                      at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134) 
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481) 
                                                                                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by ganlaw** [comment]
final String[] ids = mCameraManager.getCameraIdList();
...
mCameraId = ids[0];

ids will not have any ids if the phone has no cameras
