### ISSUE TITLE
E/Camera2: Failed to start camera preview.

### ISSUE THREAD

**Issue by flatfisher** [google/cameraview#50]
E/Camera2: Failed to start camera preview.
                                                             java.lang.IllegalStateException: Session has been closed; further changes are illegal.
                                                                 at android.hardware.camera2.impl.CameraCaptureSessionImpl.checkNotClosed(CameraCaptureSessionImpl.java:606)
                                                                 at android.hardware.camera2.impl.CameraCaptureSessionImpl.setRepeatingRequest(CameraCaptureSessionImpl.java:227)
                                                                 at com.google.android.cameraview.Camera2$2.onConfigured(Camera2.java:98)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
                                                                 at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by arriolac** [comment]
This is a duplicate of #11
