### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: previewSize must not be wider than activeArray

### ISSUE THREAD

**Issue by ankitbatra11** [google/cameraview#56]
Hi, Crashlytics is reporting following issue in production:

`Fatal Exception: java.lang.IllegalArgumentException: previewSize must not be wider than activeArray
       at android.hardware.camera2.legacy.ParameterUtils.getPreviewCropRectangleUnzoomed(ParameterUtils.java:494)
       at android.hardware.camera2.legacy.ParameterUtils.getClosestAvailableZoomCrop(ParameterUtils.java:395)
       at android.hardware.camera2.legacy.ParameterUtils.convertScalerCropRegion(ParameterUtils.java:764)
       at android.hardware.camera2.legacy.LegacyRequestMapper.convertRequestMetadata(LegacyRequestMapper.java:72)
       at android.hardware.camera2.legacy.LegacyMetadataMapper.convertRequestMetadata(LegacyMetadataMapper.java:1163)
       at android.hardware.camera2.legacy.RequestThreadManager$5.handleMessage(RequestThreadManager.java:744)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:194)
       at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by yaraki** [comment]
We should fall back to Camera1 when Camera2 is legacy implementation.
