### ISSUE TITLE
takePicture failed

### ISSUE THREAD

**Issue by JakeWoki** [google/cameraview#80]
``` Java
java.lang.RuntimeException: takePicture failed
at android.hardware.Camera.native_takePicture(Native Method)
at android.hardware.Camera.takePicture(Camera.java:1561)
at com.google.android.cameraview.Camera1.takePictureInternal(Camera1.java:230)
at com.google.android.cameraview.Camera1$2.onAutoFocus(Camera1.java:221)
at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1199)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5593)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```
Device: Honor SCL-AL00
OS: EMUI3.1.1(Android 5.1.1)
other problem:call back `onPictureTaken` and save picture always.

Camera1.java
``` Java
   @Override
    void takePicture() {
        if (!isCameraOpened()) {
            throw new IllegalStateException(
                    "Camera is not ready. Call start() before takePicture().");
        }
        if (getAutoFocus()) {
            mCamera.cancelAutoFocus();
            mCamera.autoFocus(new Camera.AutoFocusCallback() {
                @Override
                public void onAutoFocus(boolean success, Camera camera) {
                    takePictureInternal();
                }
            });
        } else {
            takePictureInternal();
        }
    }
```
takePictureInternal();
mCamera.cancelAutoFocus();
it is work.

**Comment by bzy601638015** [comment]
＋1

**Comment by anuragopenxcell** [comment]
+1, it always ends up in Camera1 irrespective of the API version

**Comment by deepikaopenxcell** [comment]
I am still getting this issue.
it is random please help me.

**Comment by krupalagile** [comment]
still getting issue

**Comment by dannyroa** [comment]
@yaraki: I have this issue as well.

**Comment by cwliu** [comment]
Getting this issue, here is the traceback:
 
![image](https://cloud.githubusercontent.com/assets/1084330/26280099/f7888802-3e0a-11e7-8fa6-7b84e1c4cb95.png)

**Comment by aswalalka** [comment]
Is it fixed, I am facing the same issue
